### ISSUE TITLE
java.net.BindException: Ne peut attribuer l'adresse demandée

### ISSUE THREAD

**Issue by docteur1** [amclauth/TrapperKeeper#1]
java.net.BindException: Ne peut attribuer l'adresse demandée
	at java.net.PlainDatagramSocketImpl.bind0(Native Method)
	at java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:93)
	at java.net.DatagramSocket.bind(DatagramSocket.java:392)
	at java.net.DatagramSocket.<init>(DatagramSocket.java:242)
	at java.net.DatagramSocket.<init>(DatagramSocket.java:299)
	at org.snmp4j.transport.DefaultUdpTransportMapping.<init>(DefaultUdpTransportMapping.java:101)
	at receivetrap.TrapReceiver.listen(TrapReceiver.java:66)
	at receivetrap.Main.main(Main.java:30)

**Comment by amclauth** [comment]
As mentioned in the readme, this often requires sudo / root to bind to an address (especially on Linux). Works in OSX and Ubuntu 18.04. That error is the error you get when you don't have permission to bind to an address.

**Comment by docteur1** [comment]
It's OK now. my IP was not correct
